version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraping-insights
    ports:
      - "8104:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    command: poetry run streamlit run src/main.py  # Run tests by default (customize as needed)
    restart: always